name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Verify release permissions 
      uses: actions/github-script@0.9.0
      env:
        GITHUB_RUN_ID: ${{github.run_id}}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const result = await github.repos.getCollaboratorPermissionLevel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            username: context.actor,
          })
          if(result.data.permission !== 'admin') {
            throw Error("User does not have permissions to release only has permissions:" + result.data)
          }
    - name: Semantic release setup 
      uses: actions/checkout@v2
    - name: Semantic release release 
      uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Wrap up release triggering issue
      uses: actions/github-script@0.9.0
      env:
        GITHUB_RUN_ID: ${{github.run_id}}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Successfully released project'
          })

